waypoints:
  - position:
      x: 0.5
      y: 0.7
      z: 1.5
    orientation:
      x: -0.707
      y: 1.0
      z: 0.0
      w: 0.707

  - position:
      x: 0.75
      y: 0.7
      z: 1.5
    orientation:
      x: -0.707
      y: 1.0
      z: 0.0
      w: 0.707